[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold Italic" }


size = 14.0

builtin_box_drawing = true

[cursor]
style = {shape = "Beam", blinking = "On"}
blink_interval = 500

[scrolling]
history = 2000
multiplier = 1

# Padding de la ventana
[window.padding]
x = 10
y = 10

[window]
#opacity = 0.93

#zellij
[terminal]
#shell = {program = "/bin/fish", args = ["zellij && clear","clear"]}
#shell = {program = "zellij", args = []}





