#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/


env = XCURSOR_SIZE,24
env = oreo_white_cursors
env = GTK_THEME= Kripton-v40                 
env = GTK_ICON_THEME=candy-icons            
env = GDK_BACKEND=wayland  